export default {
  colors: {
    primary: "var(--color-primary)",
    "primary-content": "var(--color-primary-content)",
    "primary-focus": "var(--color-primary-focus)",
    secondary: "var(--color-secondary)",
    "secondary-content": "var(--color-secondary-content)",
    "secondary-focus": "var(--color-secondary-focus)",
    accent: "var(--color-accent)",
    "accent-content": "var(--color-accent-content)",
    "accent-focus": "var(--color-accent-focus)",
    neutral: "var(--color-neutral)",
    "neutral-content": "var(--color-neutral-content)",
    "neutral-focus": "var(--color-neutral-focus)",
    success: "var(--color-success)",
    "success-content": "var(--color-success-content)",
    "success-focus": "var(--color-success-focus)",
    warning: "var(--color-warning)",
    "warning-content": "var(--color-warning-content)",
    "warning-focus": "var(--color-warning-focus)",
    danger: "var(--color-danger)",
    "danger-content": "var(--color-danger-content)",
    "danger-focus": "var(--color-danger-focus)",
    info: "var(--color-info)",
    "info-content": "var(--color-info-content)",
    "info-focus": "var(--color-info-focus)",
    error: "var(--color-error)",
    "error-content": "var(--color-error-content)",
    "error-focus": "var(--color-error-focus)",
    base: "var(--color-base)",
    "base-100": "var(--color-base-100)",
    "base-200": "var(--color-base-200)",
    "base-300": "var(--color-base-300)",
    "base-content": "var(--color-base-content)",
  },
  borderRadius: {
    box: "var(--rounded-box)",
    btn: "var(--rounded-btn)",
    badge: "var(--rounded-badge)",
  },
  spacing: {
    13: "3.25rem",
    15: "3.75rem",
    17: "4.25rem",
    18: "4.5rem",
    19: "4.75rem",
    22: "5.5rem",
    26: "6.5rem",
    30: "7.5rem",
    34: "8.5rem",
    38: "9.5rem",
    42: "10.5rem",
    46: "11.5rem",
    50: "12.5rem",
    54: "13.5rem",
    58: "14.5rem",
    62: "15.5rem",
    66: "16.5rem",
    68: "17rem",
    70: "17.5rem",
    74: "18.5rem",
    76: "19rem",
    78: "19.5rem",
    82: "20.5rem",
    84: "21rem",
    86: "21.5rem",
    88: "22rem",
    90: "22.5rem",
    92: "23rem",
    94: "23.5rem",
    98: "24.5rem",
    100: "25rem",
    128: "32rem",
    144: "36rem",
  },
  minWidth: ({ theme }: any) => ({
    ...theme("spacing"),
  }),
  minHeight: ({ theme }: any) => ({
    ...theme("spacing"),
  }),
  fontSize: {
    "2xs": "0.7rem"
  }
};
